---
title: "Pandoc Tables"
author: "BFC"
date: "29 juin 2017"
output:
  html_document: default
  pdf_document: default
---

----------------


Some Inline HTML

<style>

table {
    width: 100%;
    border-top-style: solid;
    border-top-width: medium;
    border-top-color: initial;
    border-bottom-style: solid;
    border-bottom-width: medium;
    border-bottom-color: initial;
}

</style>



```{r}
library(knitr)
library(markdown)
library(pander)
```







```{r , results='asis'}
m <- mtcars[1:3, 1:4]
pandoc.table(m, style = 'simple')
```

```{r , results='asis'}
m <- mtcars[1:3, 1:4]
pandoc.table(m, style = 'simple')
```
 
 texte
 
       &nbsp;         mpg   cyl   disp   hp 
------------------- ----- ----- ------ ----
   **Mazda RX4**     21     6    160   110 
 **Mazda RX4 Wag**   21     6    160   110 
  **Datsun 710**    22.8    4    108    93 
  
jhgj  

------------------- ----- ----- ------ ----
   **Mazda RX4**     21     6    160   110 
 **Mazda RX4 Wag**   21     6    160   110 
  **Datsun 710**    22.8    4    108    93 
------------------- ----- ----- ------ ----
 
Separation

--------

Separation


```{r , results='asis'}
m <- mtcars[1:3, 1:4]
mm <- as.matrix(m[3:8,])

colnames(mm) <- NULL
pandoc.table(mm, style = 'simple')
```


And some text to see....
